---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase
  labels:
    app: showcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showcase
  template:
    metadata:
      labels:
        app: showcase
    spec:
      containers:
        - name: showcase
          image: quay.io/openshift-knative/showcase
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: showcase
spec:
  selector:
    app: showcase
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
