ARG UBI_VERSION=8
ARG APP_VERSION=latest
FROM localhost/openshift-knative/app:${APP_VERSION} as builder

FROM registry.access.redhat.com/ubi${UBI_VERSION}/ubi-minimal
WORKDIR /work
COPY --from=builder \
  /home/quarkus/project/quarkus/target/*-runner /work/application

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
