ARG UBI_VERSION=8
ARG MANDREL_VERSION=22
ARG CONTEXT_DIR=./
ARG APP_VERSION=latest

FROM localhost/openshift-knative/frontend:${APP_VERSION} as frontend

FROM registry.access.redhat.com/quarkus/mandrel-${MANDREL_VERSION}-rhel${UBI_VERSION}

ENV HOME=/home/quarkus \
  ENV FORCE_COLOR=true

COPY --from=frontend \
  --chown=quarkus \
  /opt/app-root/.m2/repository/com/redhat/openshift/knative/showcase \
  $HOME/.m2/repository/com/redhat/openshift/knative/showcase
ADD --chown=quarkus $CONTEXT_DIR $HOME/project/quarkus
ADD --chown=quarkus $CONTEXT_DIR/../.git $HOME/project/.git
WORKDIR $HOME/project/quarkus

RUN ./mvnw -V -B --no-transfer-progress -Pnative -Dmaven.artifact.threads=50 clean dependency:go-offline
RUN ./mvnw -V -B --no-transfer-progress -Pnative package -DskipTests

FROM registry.access.redhat.com/ubi${UBI_VERSION}/ubi-minimal
WORKDIR /work
COPY --from=builder \
  /home/quarkus/project/quarkus/target/*-runner /work/application

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
