ARG UBI_VERSION=8
ARG JVM_VERSION=17
ARG CONTEXT_DIR=./
ARG APP_VERSION=latest

FROM localhost/openshift-knative/frontend:${APP_VERSION} as frontend

FROM registry.access.redhat.com/ubi${UBI_VERSION}/openjdk-${JVM_VERSION} as builder
ARG CONTEXT_DIR=./

USER root
RUN useradd --create-home --home-dir /home/quarkus quarkus
USER quarkus

ENV HOME=/home/quarkus \
  FORCE_COLOR=true

COPY --from=frontend \
  --chown=quarkus \
  /opt/app-root/.m2/repository/com/redhat/openshift/knative/showcase \
  $HOME/.m2/repository/com/redhat/openshift/knative/showcase
ADD --chown=quarkus $CONTEXT_DIR $HOME/project/quarkus
ADD --chown=quarkus $CONTEXT_DIR/../.git $HOME/project/.git
WORKDIR $HOME/project/quarkus

RUN ./mvnw -V -B --no-transfer-progress -Dstyle.color=always -Dmaven.artifact.threads=50 clean dependency:go-offline
RUN ./mvnw -V -B --no-transfer-progress -Dstyle.color=always -DskipTests package

FROM registry.access.redhat.com/ubi${UBI_VERSION}/openjdk-${JVM_VERSION}-runtime

ENV LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --from=builder \
  /home/quarkus/project/quarkus/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder \
  /home/quarkus/project/quarkus/target/quarkus-app/*.jar /deployments/
COPY --from=builder \
  /home/quarkus/project/quarkus/target/quarkus-app/app/ /deployments/app/
COPY --from=builder \
  /home/quarkus/project/quarkus/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
