---

name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'

env:
  NODE_VERSION: 16
  JDK_VERSION: 17
  JDK_DISTRO: adopt

jobs:
  expressjs:
    name: Express backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all branches and tags
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Test
        run: make expressjs
        env:
          FORCE_COLOR: 1

  quarkus:
    name: Quarkus backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all branches and tags

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}          

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JDK_DISTRO }}
          java-version: ${{ env.JDK_VERSION }}

      - name: Run Tests
        run: make quarkus
        env:
          FORCE_COLOR: 1
